{"uuid":"c866fdf2-6a3a-4de6-8e01-3d3962f7cddb","historyId":"c59643030e1e776644fd5d1d6aa79cfc","status":"failed","statusDetails":{"message":"The following error originated from your test code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Cannot find module 'undefined'\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","trace":"Error: The following error originated from your test code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Cannot find module 'undefined'\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at webpackEmptyContext (webpack:///./cypress/support/Helper/OrangeHRM_API sync:2:0)\n    at eval (webpack:///./cypress/support/Helper/OrangeHRM_API/Recruitment_ASS2_API.ts:30:49)"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"labels":[{"name":"package","value":"cypress\\e2e\\OrangeHRM\\Recruitment_Ass_2.spec.ts"}],"links":[],"start":1697300918326,"name":"An uncaught error was detected outside of a test","fullName":"An uncaught error was detected outside of a test","stop":1697300919204}